# This is a 'codegen plan': it describes a series of steps to perform
# in order to regenerate all of this project's generated code.

# a list of directories that will be cleaned
clean = ["font-tables/generated/gpos2.rs"]

# TODO: support a 'copy' step

# a mapping of files to generate, and their sources
[[generate]]
mode = "parse2"
source = "resources/codegen_inputs/gpos2.rs"
target = "font-tables/generated/gpos2.rs"
