[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

# cargo-release settings
[package.metadata.release]
release = false

[dependencies]
libfuzzer-sys = "0.4"
skrifa = { path="../skrifa" }

[[bin]]
name = "fuzz_skrifa"
path = "fuzz_targets/fuzz_skrifa.rs"
test = false
doc = false